#if !defined(ARRAYS_PARAM_H)
#define ARRAYS_PARAM_H
/* This file is automatically generated by define_array.py */

/* xf (double, 1D) [1:itot+1] */
#define XF_MIN (1)
#define XF_MAX (itot+1)
#define XF_LEN (XF_MAX-XF_MIN+1)
#define XF_MEMSIZE (sizeof(double)*XF_LEN)
#define XF(I) (xf[((I)-1)])

/* xc (double, 1D) [0:itot+1] */
#define XC_MIN (0)
#define XC_MAX (itot+1)
#define XC_LEN (XC_MAX-XC_MIN+1)
#define XC_MEMSIZE (sizeof(double)*XC_LEN)
#define XC(I) (xc[(I)])

/* dxf (double, 1D) [1:itot] */
#define DXF_MIN (1)
#define DXF_MAX (itot)
#define DXF_LEN (DXF_MAX-DXF_MIN+1)
#define DXF_MEMSIZE (sizeof(double)*DXF_LEN)
#define DXF(I) (dxf[((I)-1)])

/* dxc (double, 1D) [1:itot+1] */
#define DXC_MIN (1)
#define DXC_MAX (itot+1)
#define DXC_LEN (DXC_MAX-DXC_MIN+1)
#define DXC_MEMSIZE (sizeof(double)*DXC_LEN)
#define DXC(I) (dxc[((I)-1)])

/* yf (double, 1D) [1:jsize+1] */
#define YF_MIN (1)
#define YF_MAX (jsize+1)
#define YF_LEN (YF_MAX-YF_MIN+1)
#define YF_MEMSIZE (sizeof(double)*YF_LEN)
#define YF(J) (yf[((J)-1)])

/* yc (double, 1D) [1:jsize] */
#define YC_MIN (1)
#define YC_MAX (jsize)
#define YC_LEN (YC_MAX-YC_MIN+1)
#define YC_MEMSIZE (sizeof(double)*YC_LEN)
#define YC(J) (yc[((J)-1)])

#endif // ARRAYS_PARAM_H
